### ISSUE TITLE
add make-it-fit

### ISSUE THREAD

**Issue by joernroeder** [newmediakassel/website015#75]
@stefanendres magst du mir nen pull request machen oder ordner mit md+bild schicken?

**Comment by voec** [comment]
Mit unserem markdown interpretor. Würde folgender Text (sprich: einfacher Umbruch):

> what do you want to leave?
> who follows your traces?
> (fear not you are watched.)

auch so mit `</br>` etc. im html auftauchen? oder würde es nachher wie folgend aussehen (alles in eine Zeile zusammengerafft):

> what do you want to leave? who follows your traces? (fear not you are watched.)

wie es meistens bei markdown der Fall ist?

Der Text soll glaube ich eine Poem-artige Form haben, aber ich seh grad keinen guten Weg das in Markdown umzusetzen.
Wenn ich nach jeder Zeile doppelt Umbruch mache sieht es einfach nur chaotisch aus, besonders weil der Text auch mehrere Abschnitte hat.

**Comment by joernroeder** [comment]
@voec aus den markdown docs:

> When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return.

https://daringfireball.net/projects/markdown/syntax.php#p

**Comment by voec** [comment]
![image](https://cloud.githubusercontent.com/assets/2915643/22985877/1750dba4-f3aa-11e6-8152-5668de0effa7.png)

Thx! @joernroeder

**Comment by voec** [comment]
#80
